# Site settings
title: Hamid FzM Blog
email: contact@hamidfzm.ir
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
# the subpath of your site, e.g. /blog
url: "http://hamidfzm.ir" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hamidfzm
github_username:  hamidfzm

# Build settings
languages: ["en", "fa"]
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

gems: 
  - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
