# Site settings
title: بلاگ یه خسته
email: contact@hamidfzm.ir
author: Hamid FzM
description:
baseurl: "" 
# the subpath of your site, e.g. /blog
url: "http://hamidfzm.ir" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hamidfzm
github_username:  hamidfzm

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
livereload: true
dir: rtl
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
